"""create payments

Revision ID: 0c2c678a6c3a
Revises: a6be4dd6e216
Create Date: 2026-07-25 19:18:35.435817

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c2c678a6c3a"
down_revision: str | Sequence[str] | None = "a6be4dd6e216"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column(
            "metodo",
            sa.Enum("CREDIT_CARD", "PIX", "BOLETO", name="payment_method"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REFUSED",
                "REFUNDED",
                name="payment_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("valor", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "gateway",
            sa.String(length=50),
            server_default="MOCK",
            nullable=False,
        ),
        sa.Column("gateway_transaction_id", sa.String(length=100), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("valor > 0", name="ck_payments_valor_positive"),
        sa.ForeignKeyConstraint(["pedido_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gateway_transaction_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_payments_pedido_id"),
        "payments",
        ["pedido_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_pedido_id"), table_name="payments")
    op.drop_table("payments")
    postgresql.ENUM(
        "PENDING",
        "APPROVED",
        "REFUSED",
        "REFUNDED",
        name="payment_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(
        "CREDIT_CARD",
        "PIX",
        "BOLETO",
        name="payment_method",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
