"""create carts and cart items

Revision ID: 631a16fc0d13
Revises: 8b95cb782fba
Create Date: 2026-07-23 11:02:02.942680

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "631a16fc0d13"
down_revision: str | Sequence[str] | None = "8b95cb782fba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carts",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "ABANDONED", name="cart_status"),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_carts_usuario_id"), "carts", ["usuario_id"], unique=False)
    op.create_index(
        "uq_carts_usuario_open",
        "carts",
        ["usuario_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_table(
        "cart_items",
        sa.Column("carrinho_id", sa.Uuid(), nullable=False),
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column(
            "preco_unitario_atual",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "preco_unitario_atual > 0",
            name="ck_cart_items_preco_unitario_atual_positive",
        ),
        sa.CheckConstraint(
            "quantidade > 0",
            name="ck_cart_items_quantidade_positive",
        ),
        sa.ForeignKeyConstraint(
            ["carrinho_id"],
            ["carts.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["produto_id"],
            ["products.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "carrinho_id",
            "produto_id",
            name="uq_cart_items_carrinho_produto",
        ),
    )
    op.create_index(
        op.f("ix_cart_items_carrinho_id"),
        "cart_items",
        ["carrinho_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cart_items_produto_id"),
        "cart_items",
        ["produto_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cart_items_produto_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_carrinho_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(
        "uq_carts_usuario_open",
        table_name="carts",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index(op.f("ix_carts_usuario_id"), table_name="carts")
    op.drop_table("carts")
    postgresql.ENUM(
        "OPEN",
        "CLOSED",
        "ABANDONED",
        name="cart_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
