"""create orders and order items

Revision ID: a6be4dd6e216
Revises: 631a16fc0d13
Create Date: 2026-07-25 18:55:50.579346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6be4dd6e216"
down_revision: str | Sequence[str] | None = "631a16fc0d13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PAID",
                "SHIPPED",
                "DELIVERED",
                "CANCELED",
                name="order_status",
            ),
            server_default="PENDING_PAYMENT",
            nullable=False,
        ),
        sa.Column("valor_produtos", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "valor_frete",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("valor_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("endereco_snapshot", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valor_frete >= 0", name="ck_orders_valor_frete_non_negative"
        ),
        sa.CheckConstraint(
            "valor_produtos > 0", name="ck_orders_valor_produtos_positive"
        ),
        sa.CheckConstraint(
            "valor_total = valor_produtos + valor_frete",
            name="ck_orders_valor_total_consistent",
        ),
        sa.CheckConstraint("valor_total > 0", name="ck_orders_valor_total_positive"),
        sa.ForeignKeyConstraint(["usuario_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_usuario_id"), "orders", ["usuario_id"], unique=False
    )
    op.create_table(
        "order_items",
        sa.Column("pedido_id", sa.Uuid(), nullable=False),
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("nome_produto_snapshot", sa.String(length=200), nullable=False),
        sa.Column("sku_snapshot", sa.String(length=50), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column(
            "preco_unitario_snapshot", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("preco_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "preco_total = preco_unitario_snapshot * quantidade",
            name="ck_order_items_preco_total_consistent",
        ),
        sa.CheckConstraint(
            "preco_total > 0", name="ck_order_items_preco_total_positive"
        ),
        sa.CheckConstraint(
            "preco_unitario_snapshot > 0",
            name="ck_order_items_preco_unitario_snapshot_positive",
        ),
        sa.CheckConstraint("quantidade > 0", name="ck_order_items_quantidade_positive"),
        sa.ForeignKeyConstraint(["pedido_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["produto_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_items_pedido_id"), "order_items", ["pedido_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_items_produto_id"), "order_items", ["produto_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_produto_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_pedido_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_orders_usuario_id"), table_name="orders")
    op.drop_table("orders")
    postgresql.ENUM(
        "PENDING_PAYMENT",
        "PAID",
        "SHIPPED",
        "DELIVERED",
        "CANCELED",
        name="order_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
