"""initial

Revision ID: b0e22218cb68
Revises:
Create Date: 2026-07-11 14:58:19.915839

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b0e22218cb68"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
