"""create stocks

Revision ID: e7a302f1fdfe
Revises: aced18019ff3
Create Date: 2026-07-22 17:00:56.417095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7a302f1fdfe"
down_revision: str | Sequence[str] | None = "aced18019ff3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("produto_id", sa.Uuid(), nullable=False),
        sa.Column("quantidade", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantidade >= 0", name="ck_stocks_quantidade_non_negative"),
        sa.ForeignKeyConstraint(["produto_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stocks_produto_id"), "stocks", ["produto_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_produto_id"), table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
